services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./htdocs:/var/www/html
    depends_on:
      - php
    restart: always

  php:
    build: ./php
    container_name: php
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MEMORY_LIMIT: 128M
      UPLOAD_LIMIT: 64M
    ports:
      - 8080:80
    depends_on:
      - mysql
    restart: always

volumes:
  db_data: {}
